---

#
# Cisco DNA Center REST API
#

# Takamitsu IIDA (@takamitsu-iida)

- name: access to cisco dna center rest api
  hosts: sandboxdnac2
  gather_facts: False

  tasks:
    - name: get auth token
      # delegate_to: bastion
      iida.dnac.token:
      register: r

    - debug:
        var: r

- name: get devices from cisco dna center
  hosts: sandboxdnac2
  gather_facts: False

  tasks:
    - name: get device list
      # delegate_to: bastion
      iida.dnac.get_devices:
      register: r

    - debug:
        var: r



