---

#
# Access to Cisco DNA Center REST API
#

# 2019/12/07
# Takamitsu IIDA (@takamitsu-iida)

- name: access to cisco dna center rest api
  hosts: sandboxdnac2
  gather_facts: False

  tasks:

    - name: get auth token
      iida.dnac.token:
      register: r

    - debug:
        var: r
